server:
  port: 11001
  
debug: false
  
logging:
  level:
    '[org.springframework.session]': info 
  
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    
  datasource:
    url: jdbc:postgresql://localhost:5432/classroom
    username: classroom
    password: password
    
    hikari:
      maximum-pool-size: 10
      connection-test-query: select 1

  redis:
    host: localhost
    port: 6379
    password: P@ssw0rd
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session
    timeout: 10m
